[package]
name = "day1"
version = "0.1.0"
authors = ["Robin Message <robin@lambdacambridge.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.4.13"
line_intersection = "0.4.0"
